Repository schul-cloud/schulcloud-mobile-android, pull requests merged in 2018-07, with the labels that each got.

#126 109 - Password recovery feature added
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/schulcloud/mobile/data/datamanagers/FeedbackDataManager.java
  app/src/main/java/org/schulcloud/mobile/data/datamanagers/UserDataManager.java
  app/src/main/java/org/schulcloud/mobile/data/local/UserDatabaseHelper.java
  app/src/main/java/org/schulcloud/mobile/data/model/Account.java
  app/src/main/java/org/schulcloud/mobile/data/model/requestBodies/ResetData.java
  app/src/main/java/org/schulcloud/mobile/data/model/requestBodies/ResetRequest.java
  app/src/main/java/org/schulcloud/mobile/data/model/responseBodies/ResetResponse.java
  app/src/main/java/org/schulcloud/mobile/data/remote/RestService.java
  app/src/main/java/org/schulcloud/mobile/injection/component/ActivityComponent.java
  app/src/main/java/org/schulcloud/mobile/ui/PasswordRecovery/PasswordRecovery.java
  app/src/main/java/org/schulcloud/mobile/ui/PasswordRecovery/PasswordRecoveryMvpView.java
  app/src/main/java/org/schulcloud/mobile/ui/PasswordRecovery/PasswordRecoveryPresenter.java
  app/src/main/java/org/schulcloud/mobile/ui/signin/SignInActivity.java
  app/src/main/res/layouts/courses/layout/activity_password_recovery.xml
  app/src/main/res/layouts/signIn/layout/activity_signin.xml
  app/src/main/res/values/strings.xml
Labels: PR: ready for merge, feature

#132 Release 0.2.0
  app/build.gradle
  app/src/main/java/org/schulcloud/mobile/ui/settings/SettingsActivity.java
Labels: P1: urgent, PR: ready for merge

#135 8 Remove OnItemSelectedCallback
  app/src/main/java/org/schulcloud/mobile/controllers/base/OnItemSelectedCallback.java
  app/src/main/java/org/schulcloud/mobile/controllers/course/CourseActivity.kt
  app/src/main/java/org/schulcloud/mobile/controllers/course/TopicListAdapter.kt
  app/src/main/java/org/schulcloud/mobile/controllers/main/CourseListAdapter.kt
  app/src/main/java/org/schulcloud/mobile/controllers/main/CourseListFragment.kt
  app/src/main/res/layout/item_course.xml
  app/src/main/res/layout/item_topic.xml
Labels: PR: ready for merge

#137 5 add english translation
  app/src/main/java/org/schulcloud/mobile/controllers/main/DashboardFragment.kt
  app/src/main/java/org/schulcloud/mobile/utils/AndroidUtils.kt
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/strings.xml
Labels: PR: ready for merge

#127 Nathansen/create homework
  app/dependencies.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/schulcloud/mobile/SchulCloudApp.kt
  app/src/main/java/org/schulcloud/mobile/controllers/homework/HomeworkActivity.kt
  app/src/main/java/org/schulcloud/mobile/controllers/main/HomeworkListAdapter.kt
  app/src/main/java/org/schulcloud/mobile/controllers/main/HomeworkListFragment.kt
  app/src/main/java/org/schulcloud/mobile/controllers/main/MainActivity.kt
  app/src/main/java/org/schulcloud/mobile/jobs/GetHomeworkJob.kt
  app/src/main/java/org/schulcloud/mobile/jobs/ListUserHomeworkJob.kt
  app/src/main/java/org/schulcloud/mobile/models/homework/Homework.kt
  app/src/main/java/org/schulcloud/mobile/models/homework/HomeworkCourse.kt
  app/src/main/java/org/schulcloud/mobile/models/homework/HomeworkDao.kt
  app/src/main/java/org/schulcloud/mobile/models/homework/HomeworkRepository.kt
  app/src/main/java/org/schulcloud/mobile/models/user/UserRepository.kt
  app/src/main/java/org/schulcloud/mobile/network/ApiServiceInterface.kt
  app/src/main/java/org/schulcloud/mobile/utils/HomeworkUtils.kt
  app/src/main/java/org/schulcloud/mobile/utils/RealmUtils.kt
  app/src/main/java/org/schulcloud/mobile/utils/ViewUtils.kt
  app/src/main/java/org/schulcloud/mobile/viewmodels/HomeworkListViewModel.kt
  app/src/main/java/org/schulcloud/mobile/viewmodels/HomeworkViewModel.kt
  app/src/main/java/org/schulcloud/mobile/viewmodels/IdViewModelFactory.kt
  app/src/main/res/drawable/baseline_outlined_flag_16dp.xml
  app/src/main/res/drawable/circle_course_color.xml
  app/src/main/res/drawable/homework_card_header.xml
  app/src/main/res/layout/activity_homework.xml
  app/src/main/res/layout/fragment_homework_list.xml
  app/src/main/res/layout/item_homework.xml
  app/src/main/res/menu/activity_homework.xml
  app/src/main/res/menu/fragment_homework_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: PR: ready for merge
